//
// Translated by CS2J (http://www.cs2j.com): 1/30/2014 10:48:39 AM
//

package DIaLOGIKa.b2xtranslator.Spreadsheet.XlsFileFormat.Ptg;


public enum Ptg0x19Sub
{
    PtgNotDocumented,
    PtgAttrSemi,
    PtgAttrIf,
    __dummyEnum__0,
    PtgAttrChoose,
    __dummyEnum__1,
    __dummyEnum__2,
    __dummyEnum__3,
    PtgAttrGoto,
    __dummyEnum__4,
    __dummyEnum__5,
    __dummyEnum__6,
    __dummyEnum__7,
    __dummyEnum__8,
    __dummyEnum__9,
    __dummyEnum__10,
    PtgAttrSum,
    __dummyEnum__11,
    __dummyEnum__12,
    __dummyEnum__13,
    __dummyEnum__14,
    __dummyEnum__15,
    __dummyEnum__16,
    __dummyEnum__17,
    __dummyEnum__18,
    __dummyEnum__19,
    __dummyEnum__20,
    __dummyEnum__21,
    __dummyEnum__22,
    __dummyEnum__23,
    __dummyEnum__24,
    __dummyEnum__25,
    PtgAttrBaxcel1,
    PtgAttrBaxcel2,
    __dummyEnum__26,
    __dummyEnum__27,
    __dummyEnum__28,
    __dummyEnum__29,
    __dummyEnum__30,
    __dummyEnum__31,
    __dummyEnum__32,
    __dummyEnum__33,
    __dummyEnum__34,
    __dummyEnum__35,
    __dummyEnum__36,
    __dummyEnum__37,
    __dummyEnum__38,
    __dummyEnum__39,
    __dummyEnum__40,
    __dummyEnum__41,
    __dummyEnum__42,
    __dummyEnum__43,
    __dummyEnum__44,
    __dummyEnum__45,
    __dummyEnum__46,
    __dummyEnum__47,
    __dummyEnum__48,
    __dummyEnum__49,
    __dummyEnum__50,
    __dummyEnum__51,
    __dummyEnum__52,
    __dummyEnum__53,
    __dummyEnum__54,
    __dummyEnum__55,
    PtgAttrSpace,
    PtgAttrSpaceSemi
}

