//
// Translated by CS2J (http://www.cs2j.com): 1/30/2014 10:48:39 AM
//

package DIaLOGIKa.b2xtranslator.Spreadsheet.XlsFileFormat.Ptg;


public enum Ptg0x18Sub
{
    /*
            PtgArray = 0x40, 
            PtgFunc = 0x41, 
            PtgFuncVar = 0x42, 
            PtgName = 0x43, 
            PtgRef = 0x44, 
            PtgArea = 0x45, 
            PtgMemArea = 0x46, 
            PtgMemErr = 0x47, 
            PtgMemNoMem = 0x48, 
            PtgMemFunc = 0x49, 
            PtgRefErr = 0x4A, 
            PtgAreaErr = 0x4B, 
            PtgRefN = 0x4C, 
            PtgAreaN = 0x4D,
            PtgNameX = 0x59, 
            PtgRef3d = 0x5A, 
            PtgArea3d = 0x5B,
            PtgRefErr3d = 0x5C,
            PtgAreaErr3d = 0x5D,
            PtgArray = 0x60, 
            PtgFunc = 0x61, 
            PtgFuncVar = 0x62,
            PtgName = 0x63,
            PtgRef = 0x64,
            PtgArea = 0x65, 
            PtgMemArea = 0x66,
            PtgMemErr = 0x67,
            PtgMemNoMem = 0x68,
            PtgMemFunc = 0x69,
            PtgRefErr = 0x6A, 
            PtgAreaErr = 0x6B, 
            PtgRefN = 0x6C, 
            PtgAreaN = 0x6D,
            PtgNameX = 0x79, 
            PtgRef3d = 0x7A,
            PtgArea3d = 0x7B, 
            PtgRefErr3d = 0x7C, 
            PtgAreaErr3d = 0x7D */
    __dummyEnum__0,
    PtgElfLel,
    PtgElfRw,
    PtgElfCol,
    __dummyEnum__1,
    __dummyEnum__2,
    PtgElfRwV,
    PtgElfColV,
    __dummyEnum__3,
    __dummyEnum__4,
    PtgElfRadical,
    PtgElfRadicalS,
    __dummyEnum__5,
    PtgElfColS,
    __dummyEnum__6,
    PtgElfColSV,
    PtgElfRadicalLel,
    __dummyEnum__7,
    __dummyEnum__8,
    __dummyEnum__9,
    __dummyEnum__10,
    __dummyEnum__11,
    __dummyEnum__12,
    __dummyEnum__13,
    __dummyEnum__14,
    __dummyEnum__15,
    __dummyEnum__16,
    __dummyEnum__17,
    __dummyEnum__18,
    PtgSxName
}

